#ifndef CGAMEOFLIFE_H
#define CGAMEOFLIFE_H

#include "AEEStdDef.h"

#include "AEEInterface.h"

#if !defined(AEEINTERFACE_CPLUSPLUS)

#include "AEEStdDef.h"

//WARNING: This classID was locally generated by the wizard 11/10/2023
//For commercializing this module, please get a valid ClassID.
#define AEECLSID_CGAMEOFLIFE 0x004C479F

#else /* C++ */

#include "AEEStdDef.h"

//WARNING: This classID was locally generated by the wizard 11/10/2023
//For commercializing this module, please get a valid ClassID.
const AEECLSID AEECLSID_CGAMEOFLIFE = 0x004C479F;

#endif /* !defined(AEEINTERFACE_CPLUSPLUS) */

#endif /* #ifndef CGAMEOFLIFE_H */
